#Current Active Bookmarks  {#index}


------

## Action Items

* Build a Workflow to add these links to github
* Build an r process to manage these links and the projects related to them
    * see test.Rmd, test2.Rmd, and the remove_md() function in the Automating Git/Markdown workflow section of functions.R
* keep Blog Active
    * **[Advice to Aspiring Data Scientists: Start a Blog](http://varianceexplained.org/r/start-blog/)**


------

## Linear Algebra

[Khan Academy Linear algebra](https://www.khanacademy.org/math/linear-algebra)

[Because I've had to reference my linear algebra recommendations post several times now, here are my updated recommendations.](https://www.reddit.com/r/statistics/comments/8s9ql7/because_ive_had_to_reference_my_linear_algebra/?st=JIM9LI6I&sh=1e12e0d1)


[Best Resources to Self-Study Graduate Statistics?](https://www.reddit.com/r/statistics/comments/8jqv3l/best_resources_to_selfstudy_graduate_statistics/?st=JH8K1JLI&sh=e39322d7)


------

## key driver analysis

### Continuous and automatic key driver analysis of customer feedback

[Continuous and automatic key driver analysis of customer feedback](https://avira.github.io/dsblog/2016-11-18-customer-feedback-drivers.html)    



------

##Finalfit


### Elegant regression results tables and plots in R: the finalfit package

[Elegant regression results tables and plots in R: the finalfit package (Ewen Harrison, 2018)](https://www.r-bloggers.com/elegant-regression-results-tables-and-plots-in-r-the-finalfit-package/)    

* This article was first published on  [R – DataSurg](http://www.datasurg.net/2018/05/16/elegant-regression-results-tables-and-plots-the-finalfit-package/)    
* See Finalfit_README.Rmd


### Finalfit, knitr and R Markdown for quick results

[Finalfit, knitr and R Markdown for quick results (Harrison, 2018)](https://www.r-bloggers.com/finalfit-knitr-and-r-markdown-for-quick-results/)    

* This article was first published on  [R – DataSurg](http://www.datasurg.net/2018/05/22/finalfit-knitr-and-r-markdown-for-quick-results/)
* See Finalfit_example_1.Rmd    
* See Finalfit_example_2.Rmd



------

##Bookdown


### bookdown: Authoring Books and Technical Documents with R Markdown

[bookdown: Authoring Books and Technical Documents with R Markdown (Xie, 2018)](https://bookdown.org/yihui/bookdown/)    

* Lots of good stuff on how to use R Markdown to build books/websites, etc.


### bookdownplus package

[bookdownplus package](https://github.com/pzhaonet/bookdownplus): an R package for writing assorted books and documents, such as academic articles, mails, guitar chords, chemical molecular formulae, with R bookdown    

* Templates and stuff    
* [R bookdownplus Textbook (Zhao, 2017)](https://bookdown.org/baydap/bookdownplus/)


### Writing your thesis with bookdown

[Writing your thesis with bookdown (Berry, 2017)](https://eddjberry.netlify.com/post/writing-your-thesis-with-bookdown/)    

* Good tips and tricks


### How to Start a Bookdown Book 

[How to Start a Bookdown Book (Kross, 2016)](http://seankross.com/2016/11/17/How-to-Start-a-Bookdown-Book.html)    

* Good tips and tricks


### Mastering Software Development in R: Continuous Integration

[Mastering Software Development in R](https://bookdown.org/rdpeng/RProgDA/)    
Chapter: [Continuous Integration](https://bookdown.org/rdpeng/RProgDA/continuous-integration.html)    

* Use Travis CI to set up continuous integration for your book

###Writing your thesis with bookdown

[Writing your thesis with bookdown (Berry, 2017)](https://eddjberry.netlify.com/post/writing-your-thesis-with-bookdown/)



------

##Git


### Happy Git and GitHub for the useR

* [Happy Git and GitHub for the useR (Bryan, 2018)](http://happygitwithr.com/)
* Amazing tutorial on getting set up with git and R
* Will be a great resources for troubleshooting git/R problems
* __New Project Workflow:__
    + Creating a new project: [New project, GitHub first](http://happygitwithr.com/new-github-first.html)
    + Create a new github repository repository
    + Clone or download -> copy link
    + in RStudio -> File -> New Project -> Version Control -> Git -> paste url
* __Daily Workflow:__
    + Start day with the “Pull” button from the “Git” tab in RStudio (make sure you are starting with the current versions)
    + Save/Commit regularly with informative commit changes
* Amend Commits when you make incremental saves.  Do commits for separate changes.
* 6/11: set up git on mac:
    + installed R & RStudio on mac
    + installed git and Emacs
    + created ssh keys
    + tested push to git from shell and RStudio
    + updated this note and Committed/Pushed to git
* 6/15: set up git on PC
    + had some trouble with PC shell vs terminal, but was able to successfully connect.
    + pulled Alternate branch of this workbook to begin merge process
    + merged Alternate branch into Master to gather all links/updates as of some time last week
* Next step: [17 Existing project, GitHub first](http://happygitwithr.com/existing-github-first.html)
* Also see: http://happygitwithr.com/big-picture.html


### Learn Git Branching

[learnGitBranching](https://github.com/pcottle/learnGitBranching)

* [Learn Git Branching](https://learngitbranching.js.org/)
* Interactive introduction to git branching (learning reference), including good basic use of the terminal to enter commands
* slowly working through levels
    + 6/16: worked through Ramping up #2


### getting-started-with-git-egit-eclipse

http://jeromyanglim.blogspot.com/2010/11/getting-started-with-git-egit-eclipse.html


### Github On Demand Training

[Github On Demand Training](https://services.github.com/on-demand/)

* Most recent link: [Hello World](https://guides.github.com/activities/hello-world/)


### Other Git

http://www-cs-students.stanford.edu/~blynn/gitmagic/ch03.html

https://betterexplained.com/articles/aha-moments-when-learning-git/

https://guides.github.com/introduction/flow/?utm_source=onboarding-series&utm_medium=email&utm_content=read-the-guide-cta&utm_campaign=learn-github-flow-email

https://www.webpagefx.com/blog/web-design/git-tutorials-beginners/

[Oh Shit, Git!](https://ohshitgit.com/)


[An introduction to Git and how to use it with RStudio](https://r-bio.github.io/intro-git-rstudio/)

* Part of [The R class R programming for biologists](https://r-bio.github.io/) (which looks like a good R tutorial overall)
* 2018-06-16: high level overview of git, with some example code for what can/can't be done in RStudio

[VERSION CONTROL WITH RSTUDIO AND GITHUB](https://aberdeenstudygroup.github.io/studyGroup/lessons/SG-T1-GitHubVersionControl/VersionControl/)

* 2018-06-16: very high level overview of git with RStudio.  Jenny Bryan's happygitwithr is far superior.


[Git-Novice](https://github.com/swcarpentry/git-novice)


[Git and GitHub](http://r-pkgs.had.co.nz/git.html)



------

##Other


https://dplyr.tidyverse.org/articles/programming.html

* Good discussion of programming with dplyr (quoting, quosures, etc.)


------

# My intro to R recommendations:

* There's a whole history/background with R, but here's what I think is the most important thing to know: there are 2 popular dialects in R, and you should become familiar with both.
    * __Base R__: the base language, which can be pretty esoteric and mind-bending (but totally worth it)
    * The __tidyverse__: a group of R packages that simplify working in R. There are Base R champions that dislike the tidyverse, but I like it and highly recommend using the tidyverse to bridge the gap between beginner and advanced understanding of R.


__My intro to R recommendations (summarized):__

0. Read through the links below before starting (at least glance through them)
1. [New to R? Kickstart your learning and career with these 6 steps! – paulvanderlaken.com](https://paulvanderlaken.com/2017/10/18/learn-r/amp/) (learn R)
    * Especially [R for Data Science](https://r4ds.had.co.nz/) (tidyverse)
2. Read this: [Happy Git and GitHub for the useR](https://happygitwithr.com/) (workflow)
3. Read this: [Project-oriented workflow - Tidyverse](https://www.tidyverse.org/articles/2017/12/workflow-vs-script/) (workflow)
4. Read this: [A perfect RStudio layout (Ilya Kashnitsky, 2018)](https://www.r-bloggers.com/a-perfect-rstudio-layout/) (workflow)


## Read this "New to R" article:

* __[New to R Kickstart your learning and career with these 6 steps! – paulvanderlaken.com (Paul van der Laken, 2017)](https://paulvanderlaken.com/2017/10/18/learn-r/)__ (where I got most of these recommendations)


## Start by setting up R:

a. Create a directory for your R learning stuff somewhere on your computer.
a. Download __[A (very) short introduction to R](https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf)__ by Paul Torfs and Claudia Bauer 
    + Read the introduction and follow the steps. It will help you install all R software on your own computer and familiarize you with the standard data types.
a. We'll talk about your "R Workflow" at the end of this article


## Spend some time learning the basics of Base R:

a. You got a taste of Base R in [A (very) short introduction to R](https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf).  Follow that with Swirl and Yarrr!
a. __[Swirl](http://swirlstats.com/)__ - a course with 15 modules that provide mastery of the basics of R in the environment itself.
    + Open up your RStudio and enter the two lines of code below in your console window. 
    + `install.packages('swirl') #download swirl package`
    + `library(swirl) #load in swirl package`
    + Swirl ([webpage](http://swirlstats.com/)) will automatically start and after a couple of prompts you will be able to choose the learning course called 1: R Programming: The basics of programming in R.  
a. [__YaRrr! The Pirate’s Guide to R (Phillips, 2017)__ starting in chapter 3](https://bookdown.org/ndphillips/YaRrr/jumpin.html).
    + Start with chapter 3. It’s a fun book and will provide you with more knowledge on how to program custom functions, loops, and some basic statistical modelling techniques – the thing R was actually designed for.


## Follow that by learning the tidyverse:

+ Work through __[R for Data Science (Grolemund & Wickham, 2017)](http://r4ds.had.co.nz/)__
    + Here's a nice overview of the tidyverse: [tidyverse 101: Simplifying life for useRs – paulvanderlaken.com](https://paulvanderlaken.com/2017/07/07/tidyverse-101-simplifying-life-for-users/) 
    + Oh, and I found this quite useful: [R for Data Science Solutions](https://jrnold.github.io/r4ds-exercise-solutions/tidy-data.html)


## As you go about learning R, think about your "R workflow"" (I recommend three articles):

a. __[Happy Git and GitHub for the useR (Bryan, 2018)](http://happygitwithr.com/)__ (using git with R)
    * __New Project Workflow:__ [New project, GitHub first](http://happygitwithr.com/new-github-first.html)
        1. Create a new github repository repository
        1. Click "Clone or download" -> copy link
        1. in RStudio -> File -> New Project -> Version Control -> Git -> paste url
    * __Daily Workflow:__
        + Start day with the “Pull” button from the “Git” tab in RStudio (make sure you are starting with the current versions)
        + Save/Commit regularly with informative commit changes
        + Amend Commits when you make incremental saves.  Do commits for separate changes.
a. __[A perfect RStudio layout (Ilya Kashnitsky, 2018)](https://www.r-bloggers.com/a-perfect-rstudio-layout/)__ (My current preferred layout)
    * Adjust in “Tools” –> “Global options” –> “Pane layout”:    
        + Top Left: Source
        + Bottom Left: History (then collapse)
        + Top Right: Console
        + Bottom Right: Everything else 
a. __[Project-Oriented Workflow (Bryan 2017)](https://www.tidyverse.org/articles/2017/12/workflow-vs-script/)__ (how to think about projects in R)
    * Organize each logical project into a folder on your computer (this is also where you put your .here, .git, and/or .Rproj files) 
    * Directories:
        + Create all paths relative to the top-level directory.
        + Whenever you work on this project, launch the R process from the project’s top-level directory. If you launch R from the shell, `cd` to the correct folder first.
    * Write every script assuming it will be run in a fresh R process:
        + User-level setup: Do not save .RData when you quit R and don’t load .RData when you fire up R. 
        + Don’t do things in your .Rprofile that affect how R code runs, such as loading a package like dplyr or ggplot or setting an option such as stringsAsFactors = FALSE.
        + Daily work habit: Restart R very often and re-run your under-development script from the top.
