# Bookmarks

## R Reference

[Keyboard Shortcuts – RStudio Support](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts)

[Cookbook for R](http://www.cookbook-r.com/)

[http--www.rpad.org-Rpad-R-refcard.pdf](http://www.rpad.org/Rpad/R-refcard.pdf)

[Jonathan Baron&#39;s R help page](http://finzi.psych.upenn.edu/)   

* lots of links for r functions, blogs, and other references

[R commands](http://www.personality-project.org/r/r.commands.html)

* List of the most useful R commands

## R Graphs

[Writing functions for dplyr and ggplot2 – April 2, 2018 R-bloggers](https://www.r-bloggers.com/writing-functions-for-dplyr-and-ggplot2-april-2-2018/)

[ggplot2 - Essentials - Easy Guides - Wiki - STHDA](http://www.sthda.com/english/wiki/ggplot2-essentials)

[GitHub - hadley-ggplot2-book The ggplot2 book](https://github.com/hadley/ggplot2-book)

[Graphs](http://www.cookbook-r.com/Graphs/)

[r - Plotting multiple normal curves with ggplot2 without hardcoding means and standard deviations - Stack Overflow](https://stackoverflow.com/questions/47204418/plotting-multiple-normal-curves-with-ggplot2-without-hardcoding-means-and-standa)



## R Sentiment Analysis

[Data Science 101 Sentiment Analysis in R Tutorial No Free Hunch](http://blog.kaggle.com/2017/10/05/data-science-101-sentiment-analysis-in-r-tutorial/)


[An overview of keyword extraction techniques R-bloggers](https://www.r-bloggers.com/an-overview-of-keyword-extraction-techniques/)

[Opinion Mining, Sentiment Analysis, Opinion Extraction](https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html)

[Sentiment Analysis Using R Language Evoke Technologies](https://www.evoketechnologies.com/blog/sentiment-analysis-r-language/)

[WordCloud and Sentiment Analysis](http://rstudio-pubs-static.s3.amazonaws.com/71296_3f3ee76e8ef34410a1635926f740c473.html)



## R Stats

[Evaluating Logistic Regression Models R-bloggers](https://www.r-bloggers.com/evaluating-logistic-regression-models/)

[PCA in a tidy(verse) framework - goonR blog](https://tbradley1013.github.io/2018/02/01/pca-in-a-tidy-verse-framework/)

[wehrley.github.io-SOUPTONUTS.md at master · wehrley-wehrley.github.io · GitHub](https://github.com/wehrley/wehrley.github.io/blob/master/SOUPTONUTS.md)

[Yet Another Titanic Solve](http://rsangole.netlify.com/project/yet-another-titanic-solve/#objectives)



## R Markdown

[R Markdown](https://rmarkdown.rstudio.com/)

[Branding and Automating with R Markdown Daniel Hadley](https://www.danielphadley.com/branding-rmarkdown/)

[Document Code with R Markdown – NEON Data Skills](http://neondataskills.org/R/RMarkdown/rmd02)

[Pandoc Markdown](https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html#presentations)

[RPubs](https://rpubs.com/)

[Writing your thesis with R Markdown (3) – Figures, R code and tables Rosanna&#39;s Research](https://rosannavanhespenresearch.wordpress.com/2016/03/18/writing-your-thesis-with-r-markdown-3-figures-r-code-and-tables/)


## R Workflow / Version Control


[Git and GitHub · R packages](http://r-pkgs.had.co.nz/git.html)

[GitHub - MaximeWack-tidyflow Tidyflow a workflow that fits the tidyverse](https://github.com/MaximeWack/tidyflow)   

  * This is the workflow process that seems to work best for me right now

[Good enough practices in scientific computing](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510#sec009)

[ProjectTemplate](http://projecttemplate.net/getting_started.html)

[A perfect RStudio layout (Ilya Kashnitsky, 2018)](https://www.r-bloggers.com/a-perfect-rstudio-layout/)

  * My current preferred layout
  * Adjust in “Tools” –> “Global options” –> “Pane layout”:   
    + Top Left: Source
    + Bottom Left: History (then collapse)
    + Top Right: Console
    + Bottom Right: Everything else 


## R Projects

[Identifying &quot;Dirty&quot; Twitter Bots with R and Python – paulvanderlaken.com](https://paulvanderlaken.com/2018/03/17/identifying-dirty-twitter-bots-with-r-and-python/)

[Mapping earthquakes off the Irish Coast using the leaflet package in R R-bloggers](https://www.r-bloggers.com/mapping-earthquakes-off-the-irish-coast-using-the-leaflet-package-in-r/)

[Simulating 10 000 Tic Tac Toe Games - Analytic Freaks](http://analyticfreaks.com/simulating-10-000-tic-tac-toe-games/)



## R Blogs and general reference

[Yihui&#39;s Blog - R · statistics · life · random thoughts - Yihui Xie](https://yihui.name/en/)

[Research Tools Rosanna&#39;s Research](https://rosannavanhespenresearch.wordpress.com/category/research-tools/)

[The Litigation Articles - George D. Gopen](https://www.georgegopen.com/the-litigation-articles.html)

* Good reference on general business writing - bridging the gap between code and audience



## R links/blog posts to read

[Using R and psych for personality and psychological research](https://personality-project.org/r/psych/)

* Psych package

[Testing · R packages](http://r-pkgs.had.co.nz/tests.html)

[A Framework for Reproducible and Collaborative Data Science • workflowr](https://jdblischak.github.io/workflowr/)


[Writing better R functions part four – April 17, 2018 R-bloggers](https://www.r-bloggers.com/writing-better-r-functions-part-four-april-17-2018/)

[Announcing CGPfunctions 0.3 – April 20, 2018 R-bloggers](https://www.r-bloggers.com/announcing-cgpfunctions-0-3-april-20-2018/)

[Draw nicer Classification and Regression Trees with the rpart.plot package](http://blog.revolutionanalytics.com/2013/06/plotting-classification-and-regression-trees-with-plotrpart.html)

[cocor comparing correlations](http://comparingcorrelations.org/)

[Learning Statistics with R](http://compcogscisydney.org/learning-statistics-with-r/)

[“Are My Scores Good?” Well, Compared to What?](http://customerthink.com/are-my-scores-good-well-compared-to-what/)

http://datasciencemasters.org/

http://gitready.com/

http://happygitwithr.com/

http://happygitwithr.com/big-picture.html

http://jeromyanglim.blogspot.com/2010/11/getting-started-with-git-egit-eclipse.html

http://kbroman.org/knitr_knutshell/pages/Rmarkdown.html

http://nirvacana.com/thoughts/2013/07/08/becoming-a-data-scientist/

http://nirvacana.com/thoughts/wp-content/uploads/2018/01/RoadToDataScientist1.png

http://stat545.com/packages06_foofactors-package.html

http://uc-r.github.io/

http://varianceexplained.org/r/start-blog/

http://www.bnosac.be/index.php/blog/77-an-overview-of-keyword-extraction-techniques

http://www.dataanalysisclassroom.com/lesson36/

http://www.dataanalysisclassroom.com/lesson61/

http://www.evanmiller.org/how-not-to-sort-by-average-rating.html

http://www.feat.engineering/index.html

http://www.feat.engineering/stroke-tour.html#stroke-exploration

http://www.rcommander.com/

http://www.ryanpraski.com/apple-health-data-how-to-export-analyze-visualize-guide/

http://www.statsflowchart.co.uk/

http://www.win-vector.com/blog/2018/02/r-tip-use-qc-for-fast-legible-quoting/

http://www-cs-students.stanford.edu/~blynn/gitmagic/ch03.html

https://avira.github.io/dsblog/2016-11-18-customer-feedback-drivers.html

https://betterexplained.com/articles/aha-moments-when-learning-git/

https://blog.coursera.org/top-10-blogs-data-scientists/

https://challenge.threesixtygiving.org/faq

https://cran.r-project.org/web/packages/fuzzyjoin/fuzzyjoin.pdf

https://cran.r-project.org/web/packages/remindR/vignettes/remindR_vignette.html

https://daringfireball.net/2018/05/lobe

https://datascienceplus.com/outliers-detection-and-intervention-analysis/

https://devopedia.org/r-plotting-systems

https://dplyr.tidyverse.org/articles/programming.html

https://edomt.github.io/Intermediate-Advanced-R/

https://fivebooks.com/best-books/programming-computer-science-ana-bell/

https://github.com/bearloga/taskviewr

https://github.com/brendan-r/NPS/blob/master/R/nps_tests.R

https://github.com/first20hours/google-10000-english

https://github.com/gertstulp/ggplotgui/blob/master/README.md

https://github.com/google/CausalImpact

https://github.com/jennybc/what-they-forgot/blob/master/README.md

https://github.com/klutometis/roxygen

https://github.com/qinwf/awesome-R

https://github.com/rbind/r-podcast

https://github.com/r-lib/testthat

https://github.com/ropensci/drake/blob/master/README.md

https://github.com/seanchrismurphy/A-Psychologists-Guide-to-R

https://github.com/tidyverse/broom/blob/master/README.md

https://github.com/ujjwalkarn/DataScienceR

https://git-scm.com/book/en/v2

https://guides.github.com/introduction/flow/?utm_source=onboarding-series&utm_medium=email&utm_content=read-the-guide-cta&utm_campaign=learn-github-flow-email

https://mcfromnz.wordpress.com/2011/11/06/kaplan-meier-survival-plot-with-at-risk-table/

https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books/

https://paulvanderlaken.com/2018/02/08/rstudioconf-2018-summary/

https://r-podcast.org/episode/007-best-practices-for-workflow-management/

https://rweekly.org/

https://ryo-n7.github.io/2018-04-30-bulletchartr-package-experience/

https://speakerdeck.com/cjlortie/life-data-and-design-decisions

https://speakerdeck.com/jennybc/data-rectangling

https://stackoverflow.com/questions/2286831/how-do-you-combine-revision-control-with-workflow-for-r

https://stackoverflow.com/questions/2712421/r-and-version-control-for-the-solo-data-analyst

https://stackoverflow.com/questions/32817780/what-is-the-r-assignment-operator-for

https://statsbot.co/blog/data-scientist-resume-projects/

https://techcrunch.com/2018/05/05/lobes-ridiculously-simple-machine-learning-platform-aims-to-empower-non-technical-creators/

https://techpinions.com/top-takeaways-from-studying-iphone-x-owners/52639

https://tonyelhabr.rbind.io/posts/data-science-podcasts/

https://towardsdatascience.com/data-science-for-startups-business-intelligence-f4a2ba728e75

https://www.computerworld.com/article/2497464/business-intelligence/top-r-language-resources-to-improve-your-data-skills.html

https://www.datacamp.com/onboarding

https://www.kdnuggets.com/2018/01/primer-web-scraping-r.html/2

https://www.listendata.com/2018/03/regression-analysis.html?m=1

https://www.r-bloggers.com/analyzing-customer-data-from-square/amp/

https://www.r-bloggers.com/an-overview-of-keyword-extraction-techniques/

https://www.r-bloggers.com/an-overview-of-r-with-a-curated-learning-path/

https://www.r-bloggers.com/an-r-tutorial-visual-representation-of-complex-multivariate-relationships-using-the-r-qgraph-package-part-two-repost/

https://www.r-bloggers.com/author/chuck-powell/page/2/

https://www.r-bloggers.com/automated-feature-selection-using-bouncer/amp/

https://www.r-bloggers.com/beautiful-and-powerful-correlation-tables-in-r/amp/

https://www.r-bloggers.com/beautiful-and-powerful-correlation-tables-in-r-2/

https://www.r-bloggers.com/chaid-and-r-when-you-need-explanation-may-15-2018/

https://www.r-bloggers.com/cleaning-up-tables/

https://www.r-bloggers.com/confessions-of-a-data-scientist-why-i-quit-social-media-and-still-cut-my-own-grass/amp/

https://www.r-bloggers.com/create-your-machine-learning-library-from-scratch-with-r-2-5-pca/

https://www.r-bloggers.com/create-your-machine-learning-library-from-scratch-with-r-3-5-knn/

https://www.r-bloggers.com/data-science-for-business-course-launch-in-5-days/

https://www.r-bloggers.com/deep-learning-from-first-principles-in-python-r-and-octave-part-8/amp/

https://www.r-bloggers.com/do-clustering-by-dimensional-collapse/amp/

https://www.r-bloggers.com/enterprise-dashboards-with-r-markdown/

https://www.r-bloggers.com/exploratory-factor-analysis-in-r/

https://www.r-bloggers.com/flow-charts-in-r/amp/

https://www.r-bloggers.com/get-your-tracks-from-the-strava-api-and-plot-them-on-leaflet-maps/amp/

https://www.r-bloggers.com/greybox-package-for-r/amp/

https://www.r-bloggers.com/how-to-learn-r-2/

https://www.r-bloggers.com/how-to-plot-with-dygraphs-exercises/amp/

https://www.r-bloggers.com/icon-web-icons-for-rmarkdown/

https://www.r-bloggers.com/introducing-datazar-paper/

https://www.r-bloggers.com/intro-to-fftree-exercise/

https://www.r-bloggers.com/my-book-deep-learning-from-first-principles-now-on-amazon/

https://www.r-bloggers.com/ordinal-data/

https://www.r-bloggers.com/purrr-like-a-kitten-till-the-lake-pipes-roar/amp/

https://www.r-bloggers.com/qualitative-data-science-using-rqda-to-analyse-interviews/amp/

https://www.r-bloggers.com/rectangling-onboarding/amp/

https://www.r-bloggers.com/reliability-chapter-added-to-empirical-software-engineering-using-r/

https://www.r-bloggers.com/remove-password-protection-from-excel-sheets-using-r/amp/

https://www.r-bloggers.com/rstudioaddins-part-1-code-reproducibility-testing/amp/

https://www.r-bloggers.com/rstudioaddins-part-2-roxygen-documentation-formatting-made-easy/amp/

https://www.r-bloggers.com/slides-from-my-jax-2018-talk-deep-learning-a-primer/amp/

https://www.r-bloggers.com/statistical-sins-is-your-classification-model-any-good/amp/

https://www.r-bloggers.com/statistics-sunday-conducting-meta-analysis-in-r/amp/

https://www.r-bloggers.com/statistics-sunday-tokenizing-text/amp/

https://www.r-bloggers.com/statistics-sunday-welcome-to-sentiment-analysis-with-hotel-california/amp/

https://www.r-bloggers.com/teaching-an-advanced-r-course/

https://www.r-bloggers.com/tidying-messy-excel-data-introduction/

https://www.r-bloggers.com/to-purrr-or-not-to-purrr/

https://www.r-bloggers.com/understanding-pca-using-stack-overflow-data/amp/

https://www.r-bloggers.com/why-you-should-regret-not-going-to-erum-2018/

https://www.r-bloggers.com/wrapr-1-4-1-now-up-on-cran/amp/

https://www.r-bloggers.com/writing-better-r-functions-part-four-april-17-2018/

https://www.r-bloggers.com/x-is-for-by/amp/

https://www.r-bloggers.com/z-is-for-z-scores-and-standardizing/amp/

https://www.rdocumentation.org/trends?page1=3&sort1=direct&page2=1&sort2=total&page3=1&page4=1

https://www.reddit.com/r/dataisbeautiful/comments/8ggpfo/the_number_of_job_applications_it_took_to_become/?st=JGPAQWXW&sh=016299eb

https://www.reddit.com/r/IWantToLearn/comments/8kttv1/is_there_any_serious_computer_science_course/?st=JHFP0QUA&sh=36b7ef38

https://www.reddit.com/r/Rlanguage/comments/8gaw6t/nonstandard_evaluations_example/?st=JGOMGPPX&sh=2955447f

https://www.reddit.com/r/Rlanguage/comments/8i35fl/any_ideas_for_some_projects_i_can_do_to_show_off/?st=JGYLSTF9&sh=212e6066

https://www.reddit.com/r/Rlanguage/comments/8i35fl/any_ideas_for_some_projects_i_can_do_to_show_off/?st=JGZNXNTH&sh=dff568aa

https://www.reddit.com/r/Rlanguage/comments/8l9fgr/top_20_r_libraries_for_data_science_in_2018/?st=JHHT40NH&sh=56731e5a

https://www.reddit.com/r/rstats/comments/5t8s2h/in_rstudio_how_do_you_decide_which_code_goes_in/

https://www.reddit.com/r/rstats/comments/8arr3v/r_for_psych_students_beginner/?st=JFSBHANY&sh=b36ca40f

https://www.reddit.com/r/rstats/comments/8d04jh/anyone_tried_some_analysis_on_your_own_facebook/?st=JG47SLV2&sh=a3fdb179

https://www.reddit.com/r/rstats/comments/8ey75t/organization_best_practices_is_it_better_to_have/?st=JGFSAVJT&sh=cc463478

https://www.reddit.com/r/rstats/comments/8gh7mj/introduction_to_compositional_data_analysis_in_r/?st=JGP9AT1Z&sh=469d65da

https://www.reddit.com/r/rstats/comments/8gj0ry/every_damn_time/?st=JGPLKG6C&sh=ff75d805

https://www.reddit.com/r/rstats/comments/8gr9yt/replace_data_frame_names_in_formula_en_masse/?st=JGQZVPE7&sh=d107f53c

https://www.reddit.com/r/rstats/comments/8iokrl/resources_for_data_imputation/?st=JH28FVR8&sh=af8f2f02

https://www.reddit.com/r/rstats/comments/8jf41q/announcement_new_package_for_providing/?st=JH6XR2AV&sh=a473a57c

https://www.reddit.com/r/rstats/comments/8jkry9/publish_r_markdown_to_datascience_via_your_editor/?st=JH82ZORK&sh=1bee25d6

https://www.reddit.com/r/rstats/comments/8jui4j/machine_learning_and_its_applications/?st=JH95P6J0&sh=92ae98bd

https://www.reddit.com/r/rstats/comments/8jw5lz/soliciting_reactions_to_my_portfolio_project/?st=JH9PQ3GI&sh=ab711c9b

https://www.reddit.com/r/rstats/comments/8klfga/how_do_i_use_latent_growth_curve_analysis_in_r/?st=JHDSQQC5&sh=cae35385

https://www.reddit.com/r/rstats/comments/8ks2lj/create_waterfall_charts_using_r_ggplot2/?st=JHF037L3&sh=e1414a1c

https://www.reddit.com/r/statistics/comments/8cw4i4/errors_in_statistics_for_medical_research_any/?st=JG3RS3HY&sh=e100e2b8

https://www.reddit.com/r/statistics/comments/8e2rlp/longcateda_an_r_package_to_visualize_longitudinal/?st=JGAWBIUQ&sh=a2e2fe9d

https://www.reddit.com/r/statistics/comments/8f8mtm/odds_ratio_and_its_relevance_in_case_control/?st=JGHFVV1B&sh=aab16f60

https://www.reddit.com/r/statistics/comments/8guc0k/help_interpreting_ordinal_logistic_regression/?st=JGRGZ6KX&sh=48e9e33e

https://www.reddit.com/r/statistics/comments/8ieikb/getting_hired_as_a_data_scientist/?st=JH0U1J4K&sh=1e9a3b55

https://www.reddit.com/r/statistics/comments/8jqv3l/best_resources_to_selfstudy_graduate_statistics/?st=JH8K1JLI&sh=e39322d7

https://www.reddit.com/r/visualization/comments/8io6wo/data_visualisation_competition/?st=JH297DXI&sh=07e5f8e6

https://www.r-graph-gallery.com/pimp-my-rmd-a-few-tips-for-r-markdown/

https://www.stat.auckland.ac.nz/~paul/Reports/deviceloc/deviceloc.html

https://www.tidytextmining.com/index.html

https://www.tidyverse.org/articles/2017/12/workflow-vs-script/

https://www.webpagefx.com/blog/web-design/git-tutorials-beginners/

Package ‘fuzzyjoin’

https://www.geckoboard.com/assets/data-fallacies-to-avoid.pdf

[Bookdown main site](https://bookdown.org/)

* [blogdown: Creating Websites with R Markdown (Yihui Xie, Amber Thomas, Alison Presmanes Hill, 2017)](https://bookdown.org/yihui/blogdown/)
* lots of other book links


[Tools for Reproducible Research Spring (Broman 2016)](http://kbroman.org/Tools4RR/)  

* [Writing reproducible reports: knitr with R Markdown (Broman 2016)](http://kbroman.org/Tools4RR/assets/lectures/03_knitr_Rmd.pdf)   
* [Karl Broman (Broman 2016)](http://kbroman.org/)
     * Excellent site with lots of discussion of Reproducable research, knitr, and R overall


------

