# Other Stuff

## Python

### Python & Other Stuff - Annotated

__[The Open-Source Data Science Masters](https://github.com/datasciencemasters/go/blob/master/README.md)__


__[Need Some Beginner Friendly Projects on Github.](https://www.reddit.com/r/learnprogramming/comments/9qypf6/need_some_beginner_friendly_projects_on_github/?st=JNNKDCQU&sh=877601c8)__


__[Celebrating Five Years](https://hacktoberfest.digitalocean.com/)__


__[Best Python/Jupyter/PyCharm Experience + Report Generation With Pandoc Filters](https://www.reddit.com/r/IPython/comments/9pic5h/best_pythonjupyterpycharm_experience_report/?st=JNGDU1RC&sh=73717df9)__


__[Python for Data Science for Dummies](https://www.dummies.com/store/product/Python-for-Data-Science-For-Dummies.productCd-1118844181,navId-322449.html)__:

 * [PYTHON FOR DATA SCIENCE FOR DUMMIES CHEAT SHEET](https://www.dummies.com/programming/python/python-for-data-science-for-dummies-cheat-sheet/)
 * [Source Files](https://www.dummies.com/store/product/Python-for-Data-Science-For-Dummies.productCd-1118844181,navId-322449,descCd-DOWNLOAD.html)



### Python & Other Stuff - to read without annotation


[[GITHUB] Amazing Web Scraper for Shutterstock and GettyImages](https://www.reddit.com/r/learnpython/comments/9k9rsh/github_amazing_web_scraper_for_shutterstock_and/?st=JMPCWDJM&sh=58d14cd2)


[[P] "Mathematics for Machine Learning": Drafts for All Chapters Now Available](https://www.reddit.com/r/MachineLearning/comments/9lzabc/p_mathematics_for_machine_learning_drafts_for_all/?st=JMY6JQOR&sh=07acc4ca)


[[PySimpleGUI] Your First GUI in 5 Lines of Code](https://www.reddit.com/r/Python/comments/969rfc/pysimplegui_your_first_gui_in_5_lines_of_code/?st=JKOWVCE7&sh=3df711b9)


[[USEFUL] Collection of Good Cheatsheets](https://www.reddit.com/r/datascience/comments/9jztst/useful_collection_of_good_cheatsheets/?st=JMO8Q4P5&sh=fbe5bd98)


[15_common_mistakes_made_by_newbie_data_scientists](https://www.reddit.com/r/datascience/comments/a1lnch/15_common_mistakes_made_by_newbie_data_scientists/?st=JP3BBJE7&sh=a9fa061e)


[190 Universities Just Launched 600 Free Online Courses. Here’s the Full List.](https://qz.com/1437623/600-free-online-courses-you-can-take-from-universities-worldwide/)


[20 AI and Machine Learning Blogs](https://www.reddit.com/r/MachinesLearn/comments/9qlke6/20_ai_and_machine_learning_blogs/?st=JNLSE9K7&sh=525907c9)


[20 Minutes Tutorial for Matplotlib](https://www.reddit.com/r/Python/comments/9d4f3m/20_minutes_tutorial_for_matplotlib/?st=JLP6LESC&sh=3e3c9e02)


[91 Best Photoshop Tutorials (From Basic to Advanced)](https://www.reddit.com/r/howto/comments/91i1x5/91_best_photoshop_tutorials_from_basic_to_advanced/?st=JJZYKKH0&sh=aa42c844)


[A Complete Home Buying Calculator](https://www.reddit.com/r/visualization/comments/9f6b9u/a_complete_home_buying_calculator/?st=JLZ51NQV&sh=6672ddd4)


[A Complete Tutorial on Data Visualization With Python Using Matplotlib](https://www.reddit.com/r/Python/comments/a07icu/a_complete_tutorial_on_data_visualization_with/?st=JOX18EFK&sh=607ae2a8)


[A Facebook Engineering Manager’s Thoughts on False Beliefs in Data Science](https://www.reddit.com/r/datascience/comments/9s3ihw/a_facebook_engineering_managers_thoughts_on_false/?st=JNU9PZB1&sh=89a7edb9)


[A Good Guide for Creating Surveys and Questionnaires](https://www.reddit.com/r/psychology/comments/9hpy0i/a_good_guide_for_creating_surveys_and/?st=JMCFKLOU&sh=3ebce138)


[Adaptive Python](https://stepik.org/course/568/)


[Agile "Crash-Course" for Business Users](https://www.reddit.com/r/agile/comments/99f228/agile_crashcourse_for_business_users/?st=JL5QOFH5&sh=7f735eb1)


[Agile and Run-Run-Stop, or Test Environment Anti-Patterns](https://www.reddit.com/r/agile/comments/99vvha/agile_and_runrunstop_or_test_environment/?st=JL82AL9H&sh=2376b1f3)


[An Intuitive Explanation of Convolutional Neural Networks With Code.](https://www.reddit.com/r/Python/comments/9clfh6/an_intuitive_explanation_of_convolutional_neural/?st=JLMLRX5F&sh=bd834654)


[Anvaka/VS](https://github.com/anvaka/vs)


[Anyone Automated Their Budgeting With Python?](https://www.reddit.com/r/learnpython/comments/9uo2go/anyone_automated_their_budgeting_with_python/?st=JO6C6PX3&sh=0623f019)


[Are Pop Lyrics Getting More Repetitive?](https://pudding.cool/2017/05/song-repetition/)


[Automate the Boring Stuff](https://www.reddit.com/r/learnpython/comments/9t9wkw/automate_the_boring_stuff/?st=JNYRG7Z8&sh=fc45f259)


[Awesome-Dev-Podcasts](https://github.com/sw-yx/awesome-dev-podcasts)


[Awesome List of Important Podcasts for Software Engineers](https://github.com/rShetty/awesome-podcasts)


[Awesome Python Newsletter - Issue 124](https://www.reddit.com/r/Python/comments/9lictk/awesome_python_newsletter_issue_124/?st=JMVFEEB0&sh=039ad2b3)


[Best Practices for Python Development](https://www.reddit.com/r/Python/comments/9lwraj/best_practices_for_python_development/?st=JMXWZ39R&sh=985abf03)


[Boxplots Using Python (Way Too Much About Boxplots)](https://www.reddit.com/r/pystats/comments/9f53zb/boxplots_using_python_way_too_much_about_boxplots/?st=JLZ5AF4N&sh=729edafe)


[Chromebook Data Science - a Free Online Data Science Program for Anyone With a Web Browser. · Simply Statistics](https://www.reddit.com/r/datascience/comments/9kivvx/chromebook_data_science_a_free_online_data/?st=JMQSZ1IA&sh=2e4971b4)


[Clear All Your Doubts About Process Sigma Calculation for Both Continuous and Discrete Data Types - Most of the Trainers and Blogs Talk About DPMO Only](https://www.reddit.com/r/leansixsigma/comments/9pm8wc/clear_all_your_doubts_about_process_sigma/?st=JNGDSRVE&sh=0571414b)


[Comparison of the Most Useful Text Processing APIs](https://www.reddit.com/r/datascience/comments/9kq9bp/comparison_of_the_most_useful_text_processing_apis/?st=JMRYX3RR&sh=0e590f7f)


[Data Science - What's All the Hype About?](https://www.reddit.com/r/datasciencenews/comments/9t1qfv/data_science_whats_all_the_hype_about/?st=JNY3MS5P&sh=026c2caa)


[Data Science Ethics Checklist](https://www.reddit.com/r/datascience/comments/9shbqt/data_science_ethics_checklist/?st=JNV2O32Y&sh=6a780862)


[Data Science With R Course Series – Week 5](https://www.r-bloggers.com/data-science-with-r-course-series-week-5/)


[Data Science](https://www.galvanize.com/thank-you-ds)


[Dnd_Python_Parse](https://github.com/tomfoster70/dnd_python_parse)


[DS Book Suggestions/Recommendations Megathread](https://www.reddit.com/r/datascience/comments/8jneyb/ds_book_suggestionsrecommendations_megathread/?st=JNV2LXSS&sh=238c7723)


[Easier Than Ever to Contribute to Pygame — 15 Aug, 2018](https://www.pygame.org/news/2018/8/easier-than-ever-to-contribute-to-pygame)


[excellent_data_science_summary_for_starters](https://www.reddit.com/r/datascience/comments/9f9zsx/excellent_data_science_summary_for_starters/?st=JLZR7UA1&sh=c813f186)


[Executing Commands on Python With Google Sheets](https://www.reddit.com/r/Python/comments/9afdkm/executing_commands_on_python_with_google_sheets/?st=JLB5NRT7&sh=2f8fff64)


[For World Philosophy Day, Here's 70 Books That Philosophers Told Us They Think Everyone Should Read](https://www.reddit.com/r/philosophy/comments/9xayxt/for_world_philosophy_day_heres_70_books_that/?st=JOIQVPAD&sh=d12b2cc1)


[Free Programming Books](https://www.reddit.com/r/learnprogramming/comments/9x28gm/free_programming_books/?st=JOI5J087&sh=c8ae21ea)


[Full Stack Data Science (Transcript)](https://www.r-bloggers.com/full-stack-data-science-transcript/)


[Game Written in Python](https://www.reddit.com/r/Python/comments/960ay1/game_written_in_python/?st=JKNC9ZFR&sh=ae2ea362)


[Get Agile](https://www.reddit.com/r/agile/comments/9ck6tt/get_agile/?st=JLMRUXMF&sh=01560567)


[Getting Started](https://www.reddit.com/r/learnprogramming/wiki/faq)


[Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)


[GitHub - OmkarPathak/Django-Bookworm: a Fun Project to Store My Learning From Each Book That I Read.](https://www.reddit.com/r/coolgithubprojects/comments/9q2v2c/github_omkarpathakdjangobookworm_a_fun_project_to/?st=JNIXXLX6&sh=7f35255f)


[Good Resources for Text Analysis and NLP?](https://www.reddit.com/r/datascience/comments/96ji20/good_resources_for_text_analysis_and_nlp/?st=JKPX7ARA&sh=9c74bb8a)


[Good Resources for Text Analysis and NLP?](https://www.reddit.com/r/learnmachinelearning/comments/96hz6e/good_resources_for_text_analysis_and_nlp/?st=JKPX6RX1&sh=130584ba)


[Great Interactive Tutorial for Learning Git Branching (and More)!](https://www.reddit.com/r/programming/comments/9vjazb/great_interactive_tutorial_for_learning_git/?st=JOAICYJK&sh=0aa7d7c9)


[GROK COMPETITION BEGINNER WEEK 5 PART 2](https://www.reddit.com/r/learnpython/comments/9ca47n/grok_competition_beginner_week_5_part_2/?st=JLL5XRVM&sh=6a32f13e)


[Handy Statistics Guidebook Recommendations?](https://www.reddit.com/r/statistics/comments/9qcpzr/handy_statistics_guidebook_recommendations/?st=JNKBCKD9&sh=277f000b)


[Hitchhiker's Guide to Exploratory Data Analysis](https://www.reddit.com/r/datascience/comments/9ktgf1/hitchhikers_guide_to_exploratory_data_analysis/?st=JMS40F0Z&sh=4b639b04)


[How Can Self-Learners Learn Programming in the Most Efficient Way? a Pragmatic Approach](https://www.reddit.com/r/learnprogramming/comments/9onnrd/how_can_selflearners_learn_programming_in_the/?st=JNBXER6C&sh=73d3d4e3)


[How Do You Organize Your Python API Project? I Mean Folder Structure and Modules.](https://www.reddit.com/r/learnpython/comments/9ot7eb/how_do_you_organize_your_python_api_project_i/?st=JNCJ8BHW&sh=fe1327e4)


[How to Actually Stay Motivated to Learn How to Code](https://www.reddit.com/r/learnprogramming/comments/9rjhm0/how_to_actually_stay_motivated_to_learn_how_to/?st=JNQELUVH&sh=e6a59f6c)


[How to Create Nice Scientific Plots Using Matplotlib](https://www.reddit.com/r/learnpython/comments/9kvs9x/how_to_create_nice_scientific_plots_using/?st=JMSI824U&sh=731db010)


[How to Make Your First Serious Python Project](https://www.reddit.com/r/Python/comments/9795xf/how_to_make_your_first_serious_python_project/?st=JKTXJQCA&sh=6be2c24f)


[How to Perform Merges (Joins) on Two or More Data Frames With Base R, Tidyverse and data.table](https://www.r-bloggers.com/how-to-perform-merges-joins-on-two-or-more-data-frames-with-base-r-tidyverse-and-data-table/)


[How to Step Data Science Game Up ?](https://www.reddit.com/r/datascience/comments/9wd9qb/how_to_step_data_science_game_up/?st=JOERH2S8&sh=6d00e727)


[How We (Dropbox) Rolled Out One of the Largest Python 3 Migrations Ever](https://www.reddit.com/r/Python/comments/9iuzrm/how_we_dropbox_rolled_out_one_of_the_largest/?st=JMI9118K&sh=40bca44b)


[I Analyzed More Than 40,000 YouTube Trending Videos With Python. Here Are the Results With the Code](https://www.reddit.com/r/datascience/comments/9kpmcn/i_analyzed_more_than_40000_youtube_trending/?st=JMRTS300&sh=53a435b3)


[I Built a Simple App That Allows You to Turn Your Trained Model Into a REST Endpoint for Everyone to Use.](https://www.reddit.com/r/datascience/comments/9lg0vm/i_built_a_simple_app_that_allows_you_to_turn_your/?st=JMVFCJMD&sh=01347be2)


[I Created a Bot That Talks to Recruiters for Me (and It's Sooo Good!)](https://www.reddit.com/r/programming/comments/9v7ulj/i_created_a_bot_that_talks_to_recruiters_for_me/?st=JO907DWD&sh=edf198fe)


[I Dropped Out of School to Create My Own Data Science Master’s — Here’s My Curriculum](https://medium.com/@davidventuri/i-dropped-out-of-school-to-create-my-own-data-science-master-s-here-s-my-curriculum-1b400dcee412)


[I Just Finished Creating a Few Programs That Edit Images](https://www.reddit.com/r/learnpython/comments/9i8bjs/i_just_finished_creating_a_few_programs_that_edit/?st=JMEXZ2XN&sh=59dfb12d)


[I Made a Cheatsheet for a Co-Worker Thought It Could Be of Use Here.](https://www.reddit.com/r/learnpython/comments/9hv1ra/i_made_a_cheatsheet_for_a_coworker_thought_it/?st=JMCQHEM8&sh=f16b2433)


[I Made a Free Course for New Programmers With Strategies to Code Projects More Effectively](https://www.reddit.com/r/learnprogramming/comments/9o5nb2/i_made_a_free_course_for_new_programmers_with/?st=JN9JW9SB&sh=60e2af75)


[If You Want to Learn Programming or Need More Inspiration or Want to Watch Something Mind Blowing, Watch Handmade Hero!](https://www.reddit.com/r/learnprogramming/comments/9w1qro/if_you_want_to_learn_programming_or_need_more/?st=JODDNEK5&sh=5cda41bd)


[Introduction to Storing Data With Python](https://www.reddit.com/r/Python/comments/966pyr/introduction_to_storing_data_with_python/?st=JKOX9H0Z&sh=caf1dd75)


[Intuition of Basic Principles of Information Theory.](https://www.reddit.com/r/statistics/comments/9t7mj3/intuition_of_basic_principles_of_information/?st=JNYPQ6DX&sh=1ac0ba6e)


[Is There a Compilation of Projects to Practice Python?](https://www.reddit.com/r/learnpython/comments/9b34rz/is_there_a_compilation_of_projects_to_practice/?st=JLEGUTWV&sh=d39f8010)


[IWantToLearn](https://www.reddit.com/r/IWantToLearn/comments/9i6ugo/i_just_published_5_reasons_why_i_learned_python/?st=JMF2RG3Q&sh=ecf29d3d)


[Join GitHub Today](https://github.com/benwebber/srd5)


[Learn Git Branching](https://learngitbranching.js.org/)


[Learn to Loop the Python Way: Iterators and Generators Explained](https://www.reddit.com/r/Python/comments/9h5nyn/learn_to_loop_the_python_way_iterators_and/?st=JM9FYQE6&sh=a6de62a8)


[Lessons Learnt by Facebook Data Scientist Brandon Rohrer](https://www.reddit.com/r/datascience/comments/9l5fpk/lessons_learnt_by_facebook_data_scientist_brandon/?st=JMTTROCE&sh=1379aa44)


[Let's Learn More About Lambdas and Functional Programming in Python](https://www.reddit.com/r/datascience/comments/99d16a/lets_learn_more_about_lambdas_and_functional/?st=JL57H4XA&sh=f227534b)


[Let's Share Useful Git Hooks for Python Projects.](https://www.reddit.com/r/Python/comments/9vabpi/lets_share_useful_git_hooks_for_python_projects/?st=JO8ZCQM3&sh=326ad817)


[Linux4Noobs](https://www.reddit.com/r/linux4noobs/comments/9l2oml/a_beginners_guide_to_vim/?st=JMTS9EDS&sh=295a5c8f)


[MachinesLearn](https://www.reddit.com/r/MachinesLearn/comments/9nh3kv/top_10_ai_podcasts/?st=JN5I3U0F&sh=76522f89)


[Multi-Person Pose Estimation (Python / C++)](https://www.reddit.com/r/MachinesLearn/comments/9f4rzs/multiperson_pose_estimation_python_c/?st=JLZ5BJI6&sh=ecdc18ef)


[Mvillaloboz/Open-Source-Cs-Degree](https://github.com/mvillaloboz/open-source-cs-degree)


[My Favorite Use of Python: Clicking Through Mindless Work Slideshow Trainings.](https://www.reddit.com/r/learnpython/comments/a0xv80/my_favorite_use_of_python_clicking_through/?st=JP0HQ8G6&sh=0ac282ab)


[My Interview With Tim Harford on Misleading Statistics, Naive Predictions and Sticky Research](https://www.reddit.com/r/statistics/comments/9gtj7h/my_interview_with_tim_harford_on_misleading/?st=JM7M2779&sh=72e3a209)


[New Csvhuman Library - Read (Open) Tabular Data in the CSV Humanitarian eXchange Language (HXL) Format #Hxl #Csv #Csv10 #Humdata](https://www.reddit.com/r/opendata/comments/9vsx20/new_csvhuman_library_read_open_tabular_data_in/?st=JOBR6OXQ&sh=6fab2981)


[OneFlow - a Git Branching Model and Workflow](https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow)


[Openly Licensed Extensive Introduction to Supervised Learning With TensorFlow by Lukas Schmelzeisen (2018) Including Many Code Examples!](https://www.reddit.com/r/datascience/comments/9iqpgq/openly_licensed_extensive_introduction_to/?st=JMHOI8RI&sh=bd8a30e8)


[P1Xt's "Get Job Ready With 13 Projects, 2 Courses, and 10 Books" Guide (Web Development)](https://www.reddit.com/r/learnprogramming/comments/9vasnq/p1xts_get_job_ready_with_13_projects_2_courses/?st=JO8YXXM3&sh=f6f4a338)


[Playing and Understanding Hashable Objects](https://www.reddit.com/r/Python/comments/9aw4vb/playing_and_understanding_hashable_objects/?st=JLDIZ8GQ&sh=ad8b2446)


[Power BI in 10 Minutes: Step-by-Step Guide](https://www.reddit.com/r/visualization/comments/9va6kv/power_bi_in_10_minutes_stepbystep_guide/?st=JO8ZUP16&sh=5bf5b2a9)


[Press J to Jump to the Feed. Press Question Mark to Learn the Rest of the Keyboard Shortcuts](https://www.reddit.com/r/Python/comments/3i814b/im_writing_a_software_in_python_to_play_dungeons/?utm_source=amp&utm_medium=comment_list)


[Press J to Jump to the Feed. Press Question Mark to Learn the Rest of the Keyboard Shortcuts](https://www.reddit.com/r/Python/comments/9915qw/adding_a_pipe_operator_to_python/?st=JL3PEFEZ&sh=d4d91349)


[pybites/challenges](https://github.com/pybites/challenges)


[Python & PyCharm Setup : Getting Started](https://www.reddit.com/r/Python/comments/9ff2ny/python_pycharm_setup_getting_started/?st=JM03I7U0&sh=68c5cc88)


[Python for Data Science](https://www.edx.org/course/python-for-data-science-0)


[Python Script to Generate ASCII Art From an Image!](https://www.reddit.com/r/Python/comments/99c949/python_script_to_generate_ascii_art_from_an_image/?st=JL57JCPD&sh=c257233c)


[Python Top 10 Articles for the Past Month (v.Aug 2018)](https://www.reddit.com/r/Python/comments/96x0yu/python_top_10_articles_for_the_past_month_vaug/?st=JKS9URGF&sh=bb791565)


[Python Top 10 Articles for the Past Month (v.Sep 2018)](https://www.reddit.com/r/Python/comments/9emwil/python_top_10_articles_for_the_past_month_vsep/?st=JLWCAX5R&sh=78fbb68c)


[Reading Minds with Deep Learning](https://www.reddit.com/r/MachinesLearn/comments/a1qret/reading_minds_with_deep_learning/?st=JP44BCS8&jsh=c169a90c)


[Ron Jeffries: Developers Should Abandon Agile](https://www.reddit.com/r/agile/comments/9f4be3/ron_jeffries_developers_should_abandon_agile/?st=JLZ54L4K&sh=09ef0ccc)


[Setting Expectations for Open Source Participation](https://snarky.ca/setting-expectations-for-open-source-participation/)


[Siri Shortcuts Resources](https://www.reddit.com/r/shortcuts/comments/9k0sup/siri_shortcuts_resources/?st=JMO8SU78&sh=e7c30654)


[Six Data Science Projects to Top-Up Your Skills and Knowledge](https://www.reddit.com/r/Python/comments/97gvgi/six_data_science_projects_to_topup_your_skills/?st=JKV9VCT9&sh=a8703f5e)


[Summarize Multiple Documents in Python](https://www.reddit.com/r/Python/comments/95y076/summarize_multiple_documents_in_python/?st=JKN5877H&sh=08f345f1)


[Super Helpful Cheat Sheets for Keras, Numpy, Pandas, Scipy, Matplotlib, Scikit-Learn, Neural Networks Zoo, Ggplot2, PySpark, Dplyr and Tidyr, Jupyter Notebook](https://www.reddit.com/r/datascience/comments/9duq0l/super_helpful_cheat_sheets_for_keras_numpy_pandas/?st=JLSDSRU6&sh=4509274f)


[Super Potato Bruh - a Game Written Entirely in Python/Pygame.](https://www.reddit.com/r/Python/comments/9h76as/super_potato_bruh_a_game_written_entirely_in/?st=JM9FTYCK&sh=e6a391f9)


[TaskHero](https://www.taskheroics.com/signup/3PgojJ7wCDAQbMd86?utm_source=reddit&utm_campaign=r-productivity)


[Ten Things Python Programmers Should Know](https://www.reddit.com/r/Python/comments/9bkdbo/ten_things_python_programmers_should_know/?st=JLGSG8R0&sh=8e273604)


[The Joel Test: 12 Steps to Better Code](https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/)


[Tips and Tricks for Keeping a Healthy Git Repository](https://www.reddit.com/r/programming/comments/9qxtp9/tips_and_tricks_for_keeping_a_healthy_git/?st=JNNITS9W&sh=9b10b9e2)


[U.S. Population Growth by State (1900-2017) [OC]](https://www.reddit.com/r/dataisbeautiful/comments/9yasnn/us_population_growth_by_state_19002017_oc/?st=JONNKCPI&sh=cfc4d0f1)


[UC Berkeley Open-Sources 100K Driving Video Database](https://www.reddit.com/r/MachinesLearn/comments/9fcihu/uc_berkeley_opensources_100k_driving_video/?st=JLZR5WSO&sh=44043819)


[Ultimate List of Youtube Channels for Deep Learning and Computer Vision](https://www.reddit.com/r/MachinesLearn/comments/9lujsc/ultimate_list_of_youtube_channels_for_deep/?st=JMXF22KO&sh=fd2b9aa4)


[Upcase Is Now Free! - Loads of High Quality Tutorials on Ruby, JS, TDD, Git, Vim Etc.](https://www.reddit.com/r/learnprogramming/comments/9p72tl/upcase_is_now_free_loads_of_high_quality/?st=JNEMJ06Z&sh=8e2bf335)


[Vim-Galore: Everything You Need to Know About Vim](https://www.reddit.com/r/coolgithubprojects/comments/9okp1a/vimgalore_everything_you_need_to_know_about_vim/?st=JNBUHIR9&sh=470147dc)


[We're Launching a 'Reddit' for Jupyter Notebooks](https://www.reddit.com/r/datascience/comments/9plu6q/were_launching_a_reddit_for_jupyter_notebooks/?st=JNGC99WG&sh=e438102c)


[Webscraping Using Python and BeautifulSoup!](https://www.reddit.com/r/Python/comments/95syr4/webscraping_using_python_and_beautifulsoup/?st=JKMPIR0I&sh=8498e432)


[Welcome to Python 101!](http://python101.pythonlibrary.org/)


[What Are Some Really Cool PyCharm Plugins?](https://www.reddit.com/r/learnpython/comments/9t517l/what_are_some_really_cool_pycharm_plugins/?st=JNYPOE8I&sh=6b0e5ba8)


[What Are the Most Significant Knowledge Gaps That "Self Taught" Developers Tend to Have?](https://www.reddit.com/r/learnprogramming/comments/a1jeoa/what_are_the_most_significant_knowledge_gaps_that/?st=JP324LKH&sh=34a3c52c)


[What Data Science Courses/S You Found Best for You?](https://www.reddit.com/r/datascience/comments/9d722a/what_data_science_coursess_you_found_best_for_you/?st=JLPBBC6G&sh=44d732a5)


[What Do You Guys Use Python For?](https://www.reddit.com/r/learnpython/comments/9soa3h/what_do_you_guys_use_python_for/?st=JNW6BCL7&sh=57f9b241)


[What Is the Best Data Science Article You've Ever Read?](https://www.reddit.com/r/datascience/comments/9us4hb/what_is_the_best_data_science_article_youve_ever/?st=JO6C4WGY&sh=8b372d5d)


[What Is the Complete Work Flow of Any Data Science Project?](https://www.reddit.com/r/datascience/comments/9q9bmv/what_is_the_complete_work_flow_of_any_data/?st=JNJSJ5OD&sh=056ba32f)


[What Should I Do After CodeAcademy?](https://www.reddit.com/r/learnpython/comments/9wkeh7/what_should_i_do_after_codeacademy/?st=JOFPG9FJ&sh=7d514b4d)


[What Would You Have Told Yourself...](https://www.reddit.com/r/Python/comments/9q3aw7/what_would_you_have_told_yourself/?st=JNIYEALE&sh=64a0d59d)


[Which Is the Best Place to Learn and Practice Regular Expressions in Python?](https://www.reddit.com/r/learnpython/comments/9xlj8f/which_is_the_best_place_to_learn_and_practice/?st=JOL0VTL1&sh=3351882b)


[Why Jupyter Is Data Scientists’ Computational Notebook of Choice](https://www.reddit.com/r/datascience/comments/9swti0/why_jupyter_is_data_scientists_computational/?st=JNXEKWD9&sh=46677ad8)


[You Can Take These 600 Online Courses for Free](https://lifehacker.com/you-can-take-these-600-online-courses-for-free-1830066444)



### Python - to read without annotation



### Other Stuff - to read without annotation




------

## Surveys

[Conduct and Interpret an Ordinal Regression - Statistics Solutions](https://www.statisticssolutions.com/ordinal-regression-2/)

[How to Design and Analyze a Survey - The Ultimate Guide to Forms and Surveys Zapier](https://zapier.com/learn/forms-surveys/design-analyze-survey/)

[Ordinal Logistic Regression R Data Analysis Examples - IDRE Stats](https://stats.idre.ucla.edu/r/dae/ordinal-logistic-regression/)

[Simple Statistics for Correlating Survey Responses](https://www.joe.org/joe/2011october/tt7.php)

[Stratified Sampling Analysis](http://stattrek.com/survey-research/stratified-sampling-analysis.aspx)

[example-r-analysis-README.md at master · klmr-example-r-analysis · GitHub](https://github.com/klmr/example-r-analysis/blob/master/README.md)



------

## Fun

[HyperStat Online An Introductory Statistics Textbook and Online Tutorial for Help in Statistics Courses](http://davidmlane.com/hyperstat/index.html)

[Is It Better to Buy or Rent - NYTimes.com](http://www.nytimes.com/2007/04/10/business/2007_BUYRENT_GRAPHIC.html)

[Login - NetworthIQ](http://www.networthiq.com/login.aspx)

[The Hacker&#39;s Diet](http://www.fourmilab.ch/hackdiet/e4/)

[Role Playing with Probabilities: The Importance of Distributions](http://blog.revolutionanalytics.com/2017/11/role-playing-with-probabilities.html) 

*[RolePlayingWithProbabilities.Rmd](https://github.com/JocelynBarker/RPGStatistics/blob/master/RolePlayingWithProbabilities.Rmd)

------

## Six Sigma

[6. Process or Product Monitoring and Control](http://www.itl.nist.gov/div898/handbook/pmc/pmc.htm)

[Big Data, Data Mining, Predictive Analytics, Statistics, StatSoft Electronic Textbook](http://www.statsoft.com/textbook)

[NIST-SEMATECH e-Handbook of Statistical Methods](http://www.itl.nist.gov/div898/handbook/index.html)

[Common Quality Metrics](https://www.moresteam.com/resources/metrics.cfm)

[How To Lose Weight Using Lean Six Sigma - GoLeanSixSigma.com](https://goleansixsigma.com/how-to-lose-weight-using-lean-six-sigma/)

**[Six Sigma DMAIC Series in R – Part 3](https://www.r-bloggers.com/six-sigma-dmaic-series-in-r-part-3/)**

**[[SixSigma] Does Anyone Know of a Decent Package or Code Template for Six Sigma in R Visualisation via Ggplot2?](https://www.reddit.com/r/rstats/comments/99a3qz/sixsigma_does_anyone_know_of_a_decent_package_or/?st=JL4NORCE&sh=fe6ee7a2)**

------

## CX related

https://www.reddit.com/r/personalfinance/comments/8ho27e/shoutout_to_cfpb/?st=JGWFDE4O&sh=c1732482


[Journey Map Like A Pro: A Workshop For Customer Experience Professionals (Forrester, 2017)](https://www.forrester.com/Journey+Map+Like+A+Pro/agenda/-/E-EVE7881)

[The Customer Experience Journey Mapping Toolkit (Designing CX, 2018)](http://designingcx.com/cx-journey-mapping-toolkit/)    

* Great resource for Journey Mapping, including multiple pdf/ppt templates

[Customer Journey Mapping and CX Research (Stickdorn, 2015)](https://www.slideshare.net/MarcStickdorn1/customer-journey-mapping-cx-research-marc-stickdorn-at-ui20)

[The customer journey map (Service Design Tools, 2018)](http://www.servicedesigntools.org/tools/8)        

* Journey Map Case Studies and walkthrough        
* [CUSTOMER JOURNEY MAPPING GAME (Tallec, 2013)](https://prezi.com/1qu6lq4qucsm/customer-journey-mapping-game-transport/)         
    * Prezi of the journey mapping game (to be copied and used)

[Developing a Digital Strategy: Journey Mapping (Miller, 2015)](https://centricconsulting.com/developing-a-digital-strategy-journey-mapping/)    

* Good overview and planning thoughts for Journey Mapping

------

## Rmd stuff

```{r}
getwd()
```



```r
knitr::write_bib(file = "packages.bib")  
```


# Interview Skills

## Pre-interview prep

### Vocal warm-up exercises 
* First, arms up, deep breath in, and sigh out, ahhhhh, like that. One more time. Ahhhh, very good. 
* Now we're going to warm up our lips, and we're going to go Ba, Ba, Ba, Ba, Ba, Ba, Ba, Ba. Very good. And now, brrrrrrrrrr, just like when you were a kid. Brrrr. Now your lips should be coming alive. 
* We're going to do the tongue next with exaggerated la, la, la, la, la, la, la, la, la. Beautiful. You're getting really good at this. And then, roll an R. Rrrrrrr. That's like champagne for the tongue. 
* Finally, and if I can only do one, the pros call this the siren. It's really good. It starts with "we" and goes to "aw." The "we" is high, the "aw" is low. So you go, weeeaawww, weeeaawww. 


## Plan

* check out slack #techscreeninterviews and ask for a test interview
* mock interview with Laurie
* Get linkedin skills and endorsements from classmates
* Add ML techniques
* send Laurie details on backing up files and not using usb drives
* Projects: include a learnings and expected extensions.
* Resume updates:
    * Add Professional Profile
    * Add skills and Tools
    * Add Projects
        * Project title, brief desc, tools, affiliation, date
        * Be specific
        * For group projects, identify YOUR role
    * Formatting
        * 8-12 pts before each heading
        * 3-6 pts after each heading
        * 2-4 pts between items in the section (jobs, degrees, etc.)
* Create a personal website
* Review bio.docx and brand statement.docx


## References and links

### Ted Talks

* [10 ways to have a better conversation, CELESTE HEADLEE](https://www.ted.com/talks/celeste_headlee_10_ways_to_have_a_better_conversation?language=en )
    1. Don't multitask. And I don't mean just set down your cell phone or your tablet or your car keys or whatever is in your hand. I mean, be present. Be in that moment. Don't think about your argument you had with your boss. Don't think about what you're going to have for dinner. If you want to get out of the conversation, get out of the conversation, but don't be half in it and half out of it. 
    2. Don't pontificate. If you want to state your opinion without any opportunity for response or argument or pushback or growth, write a blog.  Now, there's a really good reason why I don't allow pundits on my show: Because they're really boring. If they're conservative, they're going to hate Obama and food stamps and abortion. If they're liberal, they're going to hate big banks and oil corporations and Dick Cheney. Totally predictable. And you don't want to be like that. You need to enter every conversation assuming that you have something to learn. The famed therapist M. Scott Peck said that true listening requires a setting aside of oneself. And sometimes that means setting aside your personal opinion. He said that sensing this acceptance, the speaker will become less and less vulnerable and more and more likely to open up the inner recesses of his or her mind to the listener. Again, assume that you have something to learn.  Bill Nye: "Everyone you will ever meet knows something that you don't." I put it this way: Everybody is an expert in something. 
    3. Use open-ended questions. In this case, take a cue from journalists. Start your questions with who, what, when, where, why or how. If you put in a complicated question, you're going to get a simple answer out. If I ask you, "Were you terrified?" you're going to respond to the most powerful word in that sentence, which is "terrified," and the answer is "Yes, I was" or "No, I wasn't." "Were you angry?" "Yes, I was very angry." Let them describe it. They're the ones that know. Try asking them things like, "What was that like?" "How did that feel?" Because then they might have to stop for a moment and think about it, and you're going to get a much more interesting response. 
    4. Go with the flow. That means thoughts will come into your mind and you need to let them go out of your mind. We've heard interviews often in which a guest is talking for several minutes and then the host comes back in and asks a question which seems like it comes out of nowhere, or it's already been answered. That means the host probably stopped listening two minutes ago because he thought of this really clever question, and he was just bound and determined to say that. And we do the exact same thing. We're sitting there having a conversation with someone, and then we remember that time that we met Hugh Jackman in a coffee shop.  And we stop listening. Stories and ideas are going to come to you. You need to let them come and let them go. 
    5. If you don't know, say that you don't know. Now, people on the radio, especially on NPR, are much more aware that they're going on the record, and so they're more careful about what they claim to be an expert in and what they claim to know for sure. Do that. Err on the side of caution. Talk should not be cheap. 
    6. Don't equate your experience with theirs. If they're talking about having lost a family member, don't start talking about the time you lost a family member. If they're talking about the trouble they're having at work, don't tell them about how much you hate your job. It's not the same. It is never the same. All experiences are individual. And, more importantly, it is not about you. You don't need to take that moment to prove how amazing you are or how much you've suffered. Somebody asked Stephen Hawking once what his IQ was, and he said, "I have no idea. People who brag about their IQs are losers."  Conversations are not a promotional opportunity. 
    7. Try not to repeat yourself. It's condescending, and it's really boring, and we tend to do it a lot. Especially in work conversations or in conversations with our kids, we have a point to make, so we just keep rephrasing it over and over. Don't do that. 
    8. Stay out of the weeds. Frankly, people don't care about the years, the names, the dates, all those details that you're struggling to come up with in your mind. They don't care. What they care about is you. They care about what you're like, what you have in common. So forget the details. Leave them out. 
    9. This is not the last one, but it is the most important one. Listen. I cannot tell you how many really important people have said that listening is perhaps the most, the number one most important skill that you could develop. Buddha said, and I'm paraphrasing, "If your mouth is open, you're not learning." And Calvin Coolidge said, "No man ever listened his way out of a job."  Why do we not listen to each other? Number one, we'd rather talk. When I'm talking, I'm in control. I don't have to hear anything I'm not interested in. I'm the center of attention. I can bolster my own identity. But there's another reason: We get distracted. The average person talks at about 225 word per minute, but we can listen at up to 500 words per minute. So our minds are filling in those other 275 words. And look, I know, it takes effort and energy to actually pay attention to someone, but if you can't do that, you're not in a conversation. You're just two people shouting out barely related sentences in the same place.  You have to listen to one another. Stephen Covey said it very beautifully. He said, "Most of us don't listen with the intent to understand. We listen with the intent to reply." 
    10. Be brief. 

* [Why the best hire might not have the perfect resume, REGINA HARTLEY](https://www.ted.com/talks/regina_hartley_why_the_best_hire_might_not_have_the_perfect_resume?referrer=playlist-talks_to_watch_before_a_job_in )
    * Talk about the adversities overcome that parallel job experiences

* [How to speak so that people want to listen, JULIAN TREASURE](https://www.ted.com/talks/julian_treasure_how_to_speak_so_that_people_want_to_listen?referrer=playlist-talks_to_watch_before_a_job_in)
    * 7 Deadly Sins of Negativity: Gossip, Judging, Negativity, Complaining, Excuses, Lying, Dogmatism
    * Founations of powerful speech: HAIL: "to greet or acclaim enthusiastically"
        * Honesty: being true in what you say, being straight and clear. 
        * Authenticity:, just being yourself. A friend of mine described it as standing in your own truth, which I think is a lovely way to put it. 
        * Integrity: being your word, actually doing what you say, and being somebody people can trust. 
        * Love: wishing people well, for two reasons. First of all, I think absolute honesty may not be what we want. I mean, my goodness, you look ugly this morning. Perhaps that's not necessary. Tempered with love, of course, honesty is a great thing. But also, if you're really wishing somebody well, it's very hard to judge them at the same time.
    * Tools which will increase the power of your speaking:
        * Register, for example. Speak from the chest. We vote for politicians with lower voices, it's true, because we associate depth with power and with authority. That's register. 
        * Timbre. It's the way your voice feels. Again, the research shows that we prefer voices which are rich, smooth, warm, like hot chocolate. 
        * Prosody. I love prosody. This is the sing-song, the meta-language that we use in order to impart meaning. It's root one for meaning in conversation. People who speak all on one note are really quite hard to listen to if they don't have any prosody at all. 
        * Pace. I can get very excited by saying something really quickly, or I can slow right down to emphasize, and at the end of that, of course, is our old friend silence. There's nothing wrong with a bit of silence in a talk, is there? We don't have to fill it with ums and ahs. It can be very powerful. 
        * Volume. (Loud) I can get really excited by using volume. Sorry about that, if I startled anybody. Or, I can have you really pay attention by getting very quiet. Some people broadcast the whole time. Try not to do that. That's called sodcasting, imposing your sound on people around you carelessly and inconsiderately. Not nice. 
    * Vocal warm-up exercises 
        * First, arms up, deep breath in, and sigh out, ahhhhh, like that. One more time. Ahhhh, very good. 
        * Now we're going to warm up our lips, and we're going to go Ba, Ba, Ba, Ba, Ba, Ba, Ba, Ba. Very good. And now, brrrrrrrrrr, just like when you were a kid. Brrrr. Now your lips should be coming alive. 
        * We're going to do the tongue next with exaggerated la, la, la, la, la, la, la, la, la. Beautiful. You're getting really good at this. And then, roll an R. Rrrrrrr. That's like champagne for the tongue. 
        * Finally, and if I can only do one, the pros call this the siren. It's really good. It starts with "we" and goes to "aw." The "we" is high, the "aw" is low. So you go, weeeaawww, weeeaawww. 
